#!/usr/bin/env python3

#
# Copyright 2025-2026 Aptivi
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software
# and associated documentation files (the “Software”), to deal in the Software without
# restriction, including without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or
# substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
# OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
# ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#

# Import JSON and XML libraries
import json

# Import other components
import os
import glob
from pathlib import Path


# Classes
class LangInfo():
    def to_dict(self):
        return {
            'lang': self.lang,
            'cultures': self.cultures,
            'locs': self.locs
        }

    def __init__(self, lang, cultures, locs):
        self.lang = lang
        self.cultures = list(cultures) or []
        self.locs = list(locs) or []


# Functions
def drl_verifypath(json_path, check_english: bool = True):
    # Check the directory
    if not os.path.isdir(json_path):
        return False
    if not check_english:
        return True

    # Now, we need to check for eng.json file since it's a descriptive file
    # for localization. That's assuming that it has either been created or
    # generated by an internal tool (from text files).
    return drl_verifylang(json_path, 'eng')


def drl_verifylang(json_path, langname: str = 'eng'):
    # Check the path
    if not drl_verifypath(json_path, False):
        return False

    # Check the language file
    json_file_path = drl_getpath(json_path, langname)
    return os.path.isfile(json_file_path)


def drl_lslangs(json_path):
    # Enumerate all files that start with *.json
    json_list = glob.glob(json_path + "/*.json")
    final_json_list = []
    for json_file in json_list:
        # Deserialize the file and verify its structure
        try:
            file_name = Path(json_file).stem
            lang_info = drl_deserialize(json_path, file_name)
            if lang_info is not None:
                final_json_list.append(file_name)
        except Exception:
            continue
    return final_json_list


def drl_getpath(json_path, langname: str = 'eng'):
    return json_path + '/' + langname + '.json'


def drl_getresxpath(resx_path, culture: str = 'en'):
    culture_pre = f'{culture}.' if culture != 'en' else ''
    file_name = 'Localizations.' + culture_pre + 'resx'
    return resx_path + '/' + file_name


def drl_genjson(json_path, langname, cultures):
    # Check the path, but make sure that we're requesting something other
    # than English. In case English gets selected (eng), we need to skip
    # the English verification.
    check_eng = langname != "eng"
    if not drl_verifypath(json_path, check_eng):
        if not check_eng:
            os.makedirs(json_path)
        else:
            raise ValueError(f"Invalid path {json_path} or no eng.json found")

    # Make a JSON representation for this language with cultures
    lang_info = LangInfo(langname, cultures, [])
    drl_genjson_final(json_path, lang_info)


def drl_genjson_final(json_path, lang_info: LangInfo):
    # Serialize the JSON language object
    json_doc = json.dumps(lang_info.to_dict(), indent=4)

    # Save this representation to a file
    json_file_path = drl_getpath(json_path, lang_info.lang)
    with open(json_file_path, 'w') as loc_file:
        loc_file.write(json_doc)


def drl_deserialize(json_path, langname):
    # Check the path
    if not drl_verifypath(json_path):
        raise ValueError(f"Invalid path {json_path} or no eng.json found")

    # Check the language
    if not drl_verifylang(json_path, langname):
        raise ValueError(f"No such language: {json_path}/{langname}.json")

    # Deserialize the JSON representation
    file_path = json_path + '/' + langname + '.json'
    lang_info = None
    with open(file_path, 'r') as lang_json_file:
        lang_json = lang_json_file.read()
        loaded_obj = json.loads(lang_json)
        loaded_lang = loaded_obj["lang"]
        loaded_cultures = loaded_obj["cultures"]
        loaded_locs = loaded_obj["locs"]
        lang_info = LangInfo(loaded_lang,
                             loaded_cultures,
                             loaded_locs)
    if lang_info is None:
        raise ValueError("Not a valid language info instance")
    return lang_info
