name: Check the script integrity

on:
  push:
  pull_request:
    
jobs:
  run-scripts:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
  
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: ${{ github.ref }}
      - name: Copy the scripts to the testsuite folder
        shell: bash
        run: |
          mkdir testsuite/tools
          cp *.cmd testsuite/tools/
          cp *.sh testsuite/tools/
      - name: Test the build script (Windows)
        if: matrix.runs-on == 'windows-latest'
        run: testsuite\tools\build.cmd
      - name: Test the clean script (Windows)
        if: matrix.runs-on == 'windows-latest'
        run: testsuite\tools\clean.cmd
      - name: Test the docgen-pack script (Windows)
        if: matrix.runs-on == 'windows-latest'
        run: testsuite\tools\docgen-pack.cmd
      - name: Test the docgen script (Windows)
        if: matrix.runs-on == 'windows-latest'
        run: testsuite\tools\docgen.cmd
      - name: Test the pack script (Windows)
        if: matrix.runs-on == 'windows-latest'
        run: testsuite\tools\pack.cmd
      - name: Test the push script (Windows)
        if: matrix.runs-on == 'windows-latest'
        run: testsuite\tools\push.cmd
      - name: Test the localization script (Windows)
        if: matrix.runs-on == 'windows-latest'
        run: testsuite\tools\localize.cmd
      - name: Test the build script (Unix)
        if: matrix.runs-on != 'windows-latest'
        run: testsuite/tools/build.sh
      - name: Test the clean script (Unix)
        if: matrix.runs-on != 'windows-latest'
        run: testsuite/tools/clean.sh
      - name: Test the docgen-pack script (Unix)
        if: matrix.runs-on != 'windows-latest'
        run: testsuite/tools/docgen-pack.sh
      - name: Test the docgen script (Unix)
        if: matrix.runs-on != 'windows-latest'
        run: testsuite/tools/docgen.sh
      - name: Test the pack script (Unix)
        if: matrix.runs-on != 'windows-latest'
        run: testsuite/tools/pack.sh
      - name: Test the push script (Unix)
        if: matrix.runs-on != 'windows-latest'
        run: testsuite/tools/push.sh
      - name: Test the localization script (Unix)
        if: matrix.runs-on != 'windows-latest'
        run: testsuite/tools/localize.sh
            
  check-scripts:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
          ref: ${{ github.ref }}
      - name: Copy the scripts to the testsuite folder
        run: |
          mkdir testsuite/tools
          cp *.cmd testsuite/tools/
          cp *.sh testsuite/tools/
      - name: Check the build script
        continue-on-error: true
        run: shellcheck testsuite/tools/build.sh -P testsuite/ -x
      - name: Check the clean script
        continue-on-error: true
        run: shellcheck testsuite/tools/clean.sh -P testsuite/ -x
      - name: Check the docgen-pack script
        continue-on-error: true
        run: shellcheck testsuite/tools/docgen-pack.sh -P testsuite/ -x
      - name: Check the docgen script
        continue-on-error: true
        run: shellcheck testsuite/tools/docgen.sh -P testsuite/ -x
      - name: Check the pack script
        continue-on-error: true
        run: shellcheck testsuite/tools/pack.sh -P testsuite/ -x
      - name: Check the push script
        continue-on-error: true
        run: shellcheck testsuite/tools/push.sh -P testsuite/ -x
      - name: Check the localization script
        continue-on-error: true
        run: shellcheck testsuite/tools/localize.sh -P testsuite/ -x